### ISSUE TITLE
blink/pulse animation

### ISSUE THREAD

**Issue by akyunus** [agtrlabs/grid_board#6]
Add a pulse animation effect which will be available through api like ``gridCell.pulse()`` for a specific GridCell

Pulse Effect example : https://codepen.io/FlorinPop17/pen/drJJzK

or a Blink animation using an overlay colored rectangle with changing opacity

**Comment by NonymousMorlock** [comment]
How exactly do you want this?, like user can set pulse to true? or call it as a constructor?..

I mean, do you want it like this

```dart
GridCell(
  //... other properties
  pulse: true
  //... other properties
),
```

or like this

```dart
GridCell.pulse(
  //... properties
)
```

**Comment by akyunus** [comment]
I thought it can be used as function of GridBoardController. So user can pulse any cell at anytime programmatically. What do you think? 
```dart
gridBoardController.pulse(cellIndex);
```
Maybe more options can be added for animation.
```dart
abstract class AnimationStyle {}
class PulseAnimation implements AnimationStyle;
//...
final animationStye = PulseAnimation(duration:Duration(milliseconds:500));
//...
gridBoardController.animate(cellIndex, animationStyle);
//...
```

**Comment by NonymousMorlock** [comment]
This makes a lot of sense, I'll do that

**Comment by NonymousMorlock** [comment]
Done with PR #9 

You can close the issue now
